--------------------------------------------------------
--  File created - Thursday-October-07-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOOKINGS
--------------------------------------------------------

  CREATE TABLE "K9SYED"."BOOKINGS" 
   (	"BOOKING_ID" NUMBER(5,0) DEFAULT 5, 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"CHECK_IN_DATE" TIMESTAMP (6), 
	"CHECK_OUT_DATE" TIMESTAMP (6), 
	"DURATION_OF_STAY" VARCHAR2(500 BYTE), 
	"PAYMENT_TYPE" VARCHAR2(500 BYTE), 
	"TOTAL_ROOMS_BOOKED" NUMBER(*,0), 
	"TOTAL_AMOUNT" NUMBER(*,0), 
	"HOTEL_ID" NUMBER(*,0), 
	"EMPLOYEE_ID" NUMBER(*,0), 
	"AMENITY_ID" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  DDL for Index BOOKING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "K9SYED"."BOOKING_PK" ON "K9SYED"."BOOKINGS" ("BOOKING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  Constraints for Table BOOKINGS
--------------------------------------------------------

  ALTER TABLE "K9SYED"."BOOKINGS" ADD CONSTRAINT "BOOKING_PK" PRIMARY KEY ("BOOKING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE"  ENABLE;
 
  ALTER TABLE "K9SYED"."BOOKINGS" MODIFY ("BOOKING_ID" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."BOOKINGS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."BOOKINGS" MODIFY ("CHECK_IN_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."BOOKINGS" MODIFY ("CHECK_OUT_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."BOOKINGS" MODIFY ("DURATION_OF_STAY" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."BOOKINGS" MODIFY ("PAYMENT_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."BOOKINGS" MODIFY ("TOTAL_ROOMS_BOOKED" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."BOOKINGS" MODIFY ("TOTAL_AMOUNT" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."BOOKINGS" MODIFY ("HOTEL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."BOOKINGS" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."BOOKINGS" MODIFY ("AMENITY_ID" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."BOOKINGS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOOKINGS
--------------------------------------------------------

    ALTER TABLE "K9SYED"."BOOKINGS" ADD CONSTRAINT "FK_BK1" FOREIGN KEY ("AMENITY_ID")
	  REFERENCES "K9SYED"."AMENITIES" ("AMENITY_ID") ENABLE;

  ALTER TABLE "K9SYED"."BOOKINGS" ADD CONSTRAINT "FK_BK2" FOREIGN KEY ("HOTEL_ID")
	  REFERENCES "K9SYED"."HOTELS" ("HOTEL_ID") ENABLE;

  ALTER TABLE "K9SYED"."BOOKINGS" ADD CONSTRAINT "FK_BK3" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "K9SYED"."EMPLOYEE" ("EMPLOYEE_ID") ENABLE;
