--------------------------------------------------------
--  File created - Thursday-October-07-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "K9SYED"."EMPLOYEE" 
   (	"EMPLOYEE_ID" NUMBER(*,0), 
	"EMPLOYEE_NAME" VARCHAR2(255 BYTE), 
	"EMP_NUMBER" NUMBER(*,0), 
	"EMPLOYEE_DEPARTMENT_NUMBER" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE" ;
 

   COMMENT ON COLUMN "K9SYED"."EMPLOYEE"."EMPLOYEE_ID" IS 'The primary key for employee';
 
   COMMENT ON COLUMN "K9SYED"."EMPLOYEE"."EMPLOYEE_NAME" IS 'Name of employee';
 
   COMMENT ON COLUMN "K9SYED"."EMPLOYEE"."EMP_NUMBER" IS 'Contact number for employee';
 
   COMMENT ON COLUMN "K9SYED"."EMPLOYEE"."EMPLOYEE_DEPARTMENT_NUMBER" IS 'Department ID for where employee works';
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "K9SYED"."EMPLOYEE_PK" ON "K9SYED"."EMPLOYEE" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "K9SYED"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE"  ENABLE;
 
  ALTER TABLE "K9SYED"."EMPLOYEE" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."EMPLOYEE" MODIFY ("EMPLOYEE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."EMPLOYEE" MODIFY ("EMP_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."EMPLOYEE" MODIFY ("EMPLOYEE_DEPARTMENT_NUMBER" NOT NULL ENABLE);
  
  ALTER TABLE "K9SYED"."EMPLOYEE" ADD CONSTRAINT FK_EMP1 FOREIGN KEY("EMPLOYEE_DEPARTMENT_NUMBER") REFERENCES "DEPARTMENT"("DEPT_ID") ENABLE;
  
  ALTER TABLE "K9SYED"."EMPLOYEE" ADD CONSTRAINT FK_EMP2 FOREIGN KEY("HOTEL_ID") REFERENCES "HOTELS"("HOTEL_ID") ENABLE;
  
  ALTER TABLE "K9SYED"."EMPLOYEE" ADD CONSTRAINT FK_EMP3 FOREIGN KEY("GUEST_ID") REFERENCES "GUEST"("GUEST_ID") ENABLE;
