--------------------------------------------------------
--  File created - Thursday-October-07-2021   
--------------------------------------------------------
--------------------------------------------    ------------
--  DDL for Table HOTEL
--------------------------------------------------------

  CREATE TABLE "K9SYED"."HOTELS" 
   (	
    "HOTEL_ID" NUMBER(*,0) DEFAULT 1, 
	"HOTEL_NAME" VARCHAR2(255 BYTE) DEFAULT 'Ryerson Hotel', 
	"HOTEL_EMAIL" VARCHAR2(255 BYTE) DEFAULT 'ryerson_hotel@gmail.com', 
	"HOTEL_NUMBER" NUMBER(*,0) DEFAULT 647123456, 
	"ROOM_COUNT" NUMBER(*,0) DEFAULT 300, 
	"OPENING_TIME" NVARCHAR2(20) DEFAULT '8:00', 
	"CLOSING_TIME" VARCHAR2(20 BYTE) DEFAULT '23:59', 
	"FLOOR_COUNT" NUMBER(*,0) DEFAULT 15, 
	"ROOM_CAPACITY" NUMBER(*,0) DEFAULT 5, 
	"DESCRIPTION_POSTAL" VARCHAR2(63 BYTE) DEFAULT 'A1B2C3', 
	"DESCRIPTION_STREET" VARCHAR2(63 BYTE) DEFAULT 'Ryerson Street', 
	"DESCRIPTION_CITY" VARCHAR2(63 BYTE) DEFAULT 'Toronto', 
	"DESCRIPTION_PROVINCE" VARCHAR2(63 BYTE) DEFAULT 'Ontario'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE" ;
 

   COMMENT ON COLUMN "K9SYED"."HOTELS"."HOTEL_ID" IS 'Primary key, used to identify the hotel';
 
   COMMENT ON COLUMN "K9SYED"."HOTELS"."HOTEL_NAME" IS 'The hotel name';
 
   COMMENT ON COLUMN "K9SYED"."HOTELS"."HOTEL_EMAIL" IS 'The hotel email';
 
   COMMENT ON COLUMN "K9SYED"."HOTELS"."HOTEL_NUMBER" IS 'Contact number for hotel';
 
   COMMENT ON COLUMN "K9SYED"."HOTELS"."ROOM_COUNT" IS 'Number of rooms in hotel';
 
   COMMENT ON COLUMN "K9SYED"."HOTELS"."OPENING_TIME" IS 'Opening time in 24 hour clock notation';
 
   COMMENT ON COLUMN "K9SYED"."HOTELS"."CLOSING_TIME" IS 'Closing time of hotel';
 
   COMMENT ON COLUMN "K9SYED"."HOTELS"."FLOOR_COUNT" IS 'Number of floors in hotel';
 
   COMMENT ON COLUMN "K9SYED"."HOTELS"."ROOM_CAPACITY" IS 'Amount of people a room can hold';
 
   COMMENT ON COLUMN "K9SYED"."HOTELS"."DESCRIPTION_POSTAL" IS 'First part of hotel description; the postal code';
 
   COMMENT ON COLUMN "K9SYED"."HOTELS"."DESCRIPTION_STREET" IS 'Second part of hotel description; Street name';
 
   COMMENT ON COLUMN "K9SYED"."HOTELS"."DESCRIPTION_CITY" IS 'City hotel is located';
--------------------------------------------------------
--  DDL for Index SYS_C00744189
--------------------------------------------------------

  CREATE UNIQUE INDEX "K9SYED"."SYS_C00744189" ON "K9SYED"."HOTELS" ("HOTEL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  Constraints for Table HOTEL
--------------------------------------------------------

  ALTER TABLE "K9SYED"."HOTELS" ADD PRIMARY KEY ("HOTEL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "DBCOURSE"  ENABLE;
 
  ALTER TABLE "K9SYED"."HOTELS" MODIFY ("HOTEL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."HOTELS" MODIFY ("HOTEL_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."HOTELS" MODIFY ("HOTEL_EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."HOTELS" MODIFY ("HOTEL_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."HOTELS" MODIFY ("ROOM_COUNT" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."HOTELS" MODIFY ("OPENING_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."HOTELS" MODIFY ("CLOSING_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."HOTELS" MODIFY ("FLOOR_COUNT" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."HOTELS" MODIFY ("ROOM_CAPACITY" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."HOTELS" MODIFY ("DESCRIPTION_POSTAL" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."HOTELS" MODIFY ("DESCRIPTION_STREET" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."HOTELS" MODIFY ("DESCRIPTION_CITY" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."HOTELS" MODIFY ("DESCRIPTION_PROVINCE" NOT NULL ENABLE);
