--------------------------------------------------------
--  File created - Thursday-October-07-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ROOM_TYPE
--------------------------------------------------------

  CREATE TABLE "K9SYED"."ROOM_TYPE" 
   (	"TYPE_ID" NUMBER, 
	"TYPE_NAME" VARCHAR2(255 BYTE), 
	"TYPE_COST" NUMBER, 
	"PET_FRIENDLY" VARCHAR2(20 BYTE), 
	"SMOKE_FRIENDLY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  DDL for Index ROOM_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "K9SYED"."ROOM_TYPE_PK" ON "K9SYED"."ROOM_TYPE" ("TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  Constraints for Table ROOM_TYPE
--------------------------------------------------------

  ALTER TABLE "K9SYED"."ROOM_TYPE" ADD CONSTRAINT "ROOM_TYPE_PK" PRIMARY KEY ("TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE"  ENABLE;
 
  ALTER TABLE "K9SYED"."ROOM_TYPE" MODIFY ("TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."ROOM_TYPE" MODIFY ("TYPE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."ROOM_TYPE" MODIFY ("TYPE_COST" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."ROOM_TYPE" MODIFY ("PET_FRIENDLY" NOT NULL ENABLE);
 
  ALTER TABLE "K9SYED"."ROOM_TYPE" MODIFY ("SMOKE_FRIENDLY" NOT NULL ENABLE);
